# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9967544e7372c5864e54528213c0293af3acf054fc58e35ed1f3f8dd24967dd1e9c1b58793f1d874ff04f5bdca11ce78fe88fb924fa3946dbd989805dd97f21

test:
  secret_key_base: 683725b26a116d55dfd3a83646e2ec7dc1308177a22e6c65307e9a912879e2f1ef56fa170ca4f610531e09d887ff7db0fcc7cf3e445e9e2cf7d9ae267fe23f40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
